# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  host: ec2-54-221-201-165.compute-1.amazonaws.com
  port: 5432
  username: bxpceuwxuzvose
  password: 'HgtakZGyVnDvPRb9S-5PEZOEFW'
  pool: 5
  timeout: 5000
  database: dbgqq0fs1o6rmm

production:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/production.sqlite3rak
